import type { CustomsOperation } from "@/lib/customs/types";

export const customsOperationMock: CustomsOperation = {
  operationId: "IMP-2025-5004993",
  framework: "CUSTOMS_COMPLIANCE",
  pedimento: "25 17 1675 5004993",
  commercialInvoice: "INV-2025-05110-A",
  certificateOfOrigin: "CO-2025-IB-05110",
  brokerExpenseAccount: "MAT89061",
  customsReference: "IB-05110-25",
  importer: "ACME INDUSTRIAL DE MONTERREY S.A. DE C.V.",
  provider: "GLOBAL PARTS INC.",
  broker: "TRANSPORTES FRONTERA S.C.",
  metrics: {
    auditedOperations: 1,
    igiPaid: 36285.37,
    brokerAccountTotal: 151155.2,
    potentialRecovery: 36285.37,
    riskScore: 82,
    riskScoreAverage: 82,
    criticalFindings: 4,
    severity: "High",
  },
  documents: [
    {
      id: "doc-pedimento",
      documentType: "pedimento",
      label: "Pedimento",
      filename: "25-17-1675-5004993.pdf",
      required: true,
      status: "Mock loaded",
    },
    {
      id: "doc-invoice",
      documentType: "commercial_invoice",
      label: "Facturas Comerciales",
      filename: "INV-2025-05110-A.pdf",
      required: true,
      status: "Mock loaded",
    },
    {
      id: "doc-bill-of-lading",
      documentType: "bill_of_lading",
      label: "Bill of Lading",
      filename: "BL-IB-05110-25.pdf",
      required: true,
      status: "Mock loaded",
    },
    {
      id: "doc-certificate",
      documentType: "certificate_of_origin",
      label: "Certificado de Origen T-MEC",
      filename: "CO-2025-IB-05110.pdf",
      required: false,
      status: "Optional",
    },
    {
      id: "doc-expense-account",
      documentType: "broker_expense_account",
      label: "Cuenta de Gastos",
      filename: "MAT89061.pdf",
      required: true,
      status: "Mock loaded",
    },
    {
      id: "doc-cfdi-pdf",
      documentType: "cfdi_pdf",
      label: "CFDI PDF",
      filename: "CFDI-MAT89061.pdf",
      required: true,
      status: "Mock loaded",
    },
    {
      id: "doc-cfdi-xml",
      documentType: "cfdi_xml",
      label: "CFDI XML",
      filename: "CFDI-MAT89061.xml",
      required: true,
      status: "Mock loaded",
    },
    {
      id: "doc-data-sheet",
      documentType: "data_sheet",
      label: "Hoja de Datos",
      filename: "HOJA-DATOS-IB-05110-25.pdf",
      required: true,
      status: "Mock loaded",
    },
    {
      id: "doc-cove",
      documentType: "cove",
      label: "COVE",
      filename: "COVE-5004993.pdf",
      required: false,
      status: "Optional",
    },
  ],
  findings: [
    {
      id: "CUSTOMS_TMEC_IGI_001",
      severity: "High",
      rule: "T-MEC / IGI preferencial",
      description:
        "Posible sobrepago por no aplicar preferencia T-MEC; el pedimento declara origen USA y el expediente contiene certificado CO-2025-IB-05110.",
      potentialRecovery: 36285.37,
      status: "Open",
      evidence: "Expediente IMP-2025-5004993, pedimento 25 17 1675 5004993, factura INV-2025-05110-A y certificado CO-2025-IB-05110.",
      recommendation: "Validar cobertura del certificado y preparar solicitud de rectificacion o recuperacion.",
    },
    {
      id: "CUSTOMS_SAT_DIFF_001",
      severity: "High",
      rule: "Conciliacion SAT",
      description: "Diferencia entre total SAT declarado en pedimento y total trasladado en cuenta de gastos.",
      potentialRecovery: 0,
      status: "In Review",
      evidence: "Cuenta de gastos MAT89061 contra contribuciones del pedimento.",
      recommendation: "Solicitar desglose SAT al agente aduanal y conciliar linea por linea.",
    },
    {
      id: "CUSTOMS_SLA_FEES_001",
      severity: "Medium",
      rule: "Honorarios vs SLA",
      description: "Honorarios del agente aduanal por arriba de la tarifa pactada para operaciones de importacion.",
      potentialRecovery: 0,
      status: "Open",
      evidence: "Cuenta de gastos MAT89061 y condiciones pactadas con TRANSPORTES FRONTERA S.C.",
      recommendation: "Recalcular honorarios conforme al SLA vigente y solicitar nota de credito si procede.",
    },
    {
      id: "CUSTOMS_UNAUTHORIZED_CHARGES_001",
      severity: "Medium",
      rule: "Cargos autorizados",
      description: "Se detectan conceptos logisticos no contemplados en SLA ni soportados por comprobante asociado.",
      potentialRecovery: 0,
      status: "Open",
      evidence: "Conceptos varios incluidos en la cuenta de gastos del agente aduanal.",
      recommendation: "Clasificar cargos, pedir soporte documental y bloquear conceptos no autorizados en siguientes operaciones.",
    },
  ],
  dictamen:
    "El expediente aduanal IMP-2025-5004993 presenta riesgo alto por posible recuperacion de IGI y diferencias documentales entre pedimento, facturas, cuenta de gastos y anexos. El principal caso de negocio es validar la aplicacion T-MEC para recuperar 36,285.37 MXN potenciales.",
  recommendations: [
    "Validar juridicamente la preferencia T-MEC antes de iniciar rectificacion.",
    "Solicitar al agente aduanal desglose de contribuciones SAT y soporte de cargos logisticos.",
    "Configurar un catalogo de cargos autorizados por SLA para prevenir reincidencias.",
  ],
  nextSteps: [
    "Aprobar revision documental del expediente piloto.",
    "Normalizar extractos de pedimento, facturas, CFDI, hoja de datos, certificado y cuenta de gastos.",
    "Preparar tablero comparativo para carga masiva de expedientes aduanales.",
  ],
};

export const customsKpis = [
  {
    label: "Operaciones Auditadas",
    value: String(customsOperationMock.metrics.auditedOperations),
    hint: customsOperationMock.operationId,
  },
  {
    label: "Recuperacion Potencial",
    value: formatCurrency(customsOperationMock.metrics.potentialRecovery),
    hint: "IGI pagado",
  },
  {
    label: "Hallazgos Criticos",
    value: String(customsOperationMock.metrics.criticalFindings),
    hint: customsOperationMock.metrics.severity,
  },
  {
    label: "Risk Score Promedio",
    value: String(customsOperationMock.metrics.riskScoreAverage),
    hint: "Alto",
  },
];

export function formatCurrency(value: number) {
  return new Intl.NumberFormat("es-MX", {
    currency: "MXN",
    maximumFractionDigits: 2,
    minimumFractionDigits: 2,
    style: "currency",
  }).format(value);
}
